steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'pull-shippingservice'
  entrypoint: 'bash'
  args:
   - '-c'
   - |
     docker pull gcr.io/$PROJECT_ID/shippingservice:latest || exit 0
- name: 'gcr.io/cloud-builders/docker'
  id: 'build-shippingservice'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/shippingservice:latest', '.', '--cache-from', 'gcr.io/$PROJECT_ID/shippingservice:latest']
  timeout: 600s
  waitFor:
    - 'pull-shippingservice'
- name: 'gcr.io/cloud-builders/docker'
  id: 'push-shippingservice'
  args: ['push', 'gcr.io/$PROJECT_ID/shippingservice:latest']
  waitFor:
    - 'build-shippingservice'
images:
  - 'gcr.io/$PROJECT_ID/shippingservice:latest'