steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'pull-cartservice'
  entrypoint: 'bash'
  args:
   - '-c'
   - |
     docker pull gcr.io/$PROJECT_ID/cartservice:latest || exit 0
- name: 'gcr.io/cloud-builders/docker'
  id: 'build-cartservice'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/cartservice:latest', '.', '--cache-from', 'gcr.io/$PROJECT_ID/cartservice:latest']
  timeout: 600s
  waitFor:
    - 'pull-cartservice'
- name: 'gcr.io/cloud-builders/docker'
  id: 'push-cartservice'
  args: ['push', 'gcr.io/$PROJECT_ID/cartservice:latest']
  waitFor:
    - 'build-cartservice'
images:
  - 'gcr.io/$PROJECT_ID/cartservice:latest'