steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'pull-frontend'
  entrypoint: 'bash'
  args:
   - '-c'
   - |
     docker pull gcr.io/$PROJECT_ID/frontend:latest || exit 0
- name: 'gcr.io/cloud-builders/docker'
  id: 'build-frontend'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/frontend:latest', '.', '--cache-from', 'gcr.io/$PROJECT_ID/frontend:latest']
  timeout: 600s
  waitFor:
    - 'pull-frontend'
- name: 'gcr.io/cloud-builders/docker'
  id: 'push-frontend'
  args: ['push', 'gcr.io/$PROJECT_ID/frontend:latest']
  waitFor:
    - 'build-frontend'
images:
  - 'gcr.io/$PROJECT_ID/frontend:latest'