steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'pull-productcatalogservice'
  entrypoint: 'bash'
  args:
   - '-c'
   - |
     docker pull gcr.io/$PROJECT_ID/productcatalogservice:latest || exit 0
- name: 'gcr.io/cloud-builders/docker'
  id: 'build-productcatalogservice'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/productcatalogservice:latest', '.', '--cache-from', 'gcr.io/$PROJECT_ID/productcatalogservice:latest']
  timeout: 600s
  waitFor:
    - 'pull-productcatalogservice'
- name: 'gcr.io/cloud-builders/docker'
  id: 'push-productcatalogservice'
  args: ['push', 'gcr.io/$PROJECT_ID/productcatalogservice:latest']
  waitFor:
    - 'build-productcatalogservice'
images:
  - 'gcr.io/$PROJECT_ID/productcatalogservice:latest'